services:
  # Backend Go
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Sao_Paulo
      - PORT=${PORT:-8080}
      - GIN_MODE=${GIN_MODE:-release}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres123}
      - POSTGRES_DB=${POSTGRES_DB:-to_de_olho}
      - REDIS_ADDR=${REDIS_ADDR:-redis:6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todo-network
    restart: unless-stopped
    command: ["./server"]
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8080/api/v1}
    container_name: todo-frontend
    ports:
      - "3000:3000"
    environment:
      - TZ=America/Sao_Paulo
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080/api/v1}
    depends_on:
      - backend
    networks:
      - todo-network
    restart: unless-stopped

  # Banco de Dados Principal
  postgres:
    image: postgres:16-alpine
    container_name: todo-postgres
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: ${POSTGRES_DB:-to_de_olho}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    networks:
      - todo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Cache Redis
  redis:
    image: redis:7-alpine
    container_name: todo-redis
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - todo-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  # Ingestor Inteligente (verifica automaticamente se precisa executar backfill)
  ingestor:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres123}
      - POSTGRES_DB=${POSTGRES_DB:-to_de_olho}
      - CAMARA_CLIENT_RPS=${CAMARA_CLIENT_RPS:-2}
      - CAMARA_CLIENT_BURST=${CAMARA_CLIENT_BURST:-4}
      - CAMARA_CLIENT_TIMEOUT=${CAMARA_CLIENT_TIMEOUT:-30s}
      - CAMARA_CLIENT_BASE_URL=${CAMARA_CLIENT_BASE_URL:-https://dadosabertos.camara.leg.br/api/v2}
      # Configuração inteligente de backfill
      - BACKFILL_START_YEAR=${BACKFILL_START_YEAR:-2022}
      - BACKFILL_END_YEAR=${BACKFILL_END_YEAR:-0}
      - BACKFILL_TRIGGERED_BY=docker-compose
      - BACKFILL_WORKERS=${BACKFILL_WORKERS:-2}
      - BACKFILL_BATCH_SIZE=${BACKFILL_BATCH_SIZE:-100}
    networks:
      - todo-network
    command: ["./smart-init.sh"]
    restart: "no"

  # Scheduler (sincronização incremental automática)
  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-scheduler
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ingestor:
        condition: service_started
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres123}
      - POSTGRES_DB=${POSTGRES_DB:-to_de_olho}
      - REDIS_ADDR=${REDIS_ADDR:-redis:6379}
      - CAMARA_CLIENT_RPS=${CAMARA_CLIENT_RPS:-2}
      - CAMARA_CLIENT_BURST=${CAMARA_CLIENT_BURST:-4}
      - CAMARA_CLIENT_TIMEOUT=${CAMARA_CLIENT_TIMEOUT:-30s}
      - CAMARA_CLIENT_BASE_URL=${CAMARA_CLIENT_BASE_URL:-https://dadosabertos.camara.leg.br/api/v2}
      - SCHEDULER_PARALLEL_WORKERS=${SCHEDULER_PARALLEL_WORKERS:-3}
    networks:
      - todo-network
    command: ["./scheduler"]
    restart: unless-stopped

  # Adminer (UI para Postgres)
  adminer:
    image: adminer:4.8.1
    container_name: todo-adminer
    environment:
      - TZ=America/Sao_Paulo
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todo-network
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  todo-network:
    driver: bridge
